# Dockerfile.frontend
FROM node:16-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Copy the frontend files into the Nginx container
#COPY ./frontend /usr/share/nginx/html
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
